const countryCatalog = Object.freeze({
  AUT: { name: "Austria", continent: "Europa" },
  BEL: { name: "Belgia", continent: "Europa" },
  BGR: { name: "Bułgaria", continent: "Europa" },
  BIH: { name: "Bośnia i Hercegowina", continent: "Europa" },
  CHE: { name: "Szwajcaria", continent: "Europa" },
  CYP: { name: "Cypr", continent: "Europa" },
  CZE: { name: "Czechy", continent: "Europa" },
  DEU: { name: "Niemcy", continent: "Europa" },
  DNK: { name: "Dania", continent: "Europa" },
  ESP: { name: "Hiszpania", continent: "Europa" },
  EST: { name: "Estonia", continent: "Europa" },
  FIN: { name: "Finlandia", continent: "Europa" },
  FRA: { name: "Francja", continent: "Europa" },
  GBR: { name: "Wielka Brytania", continent: "Europa" },
  HRV: { name: "Chorwacja", continent: "Europa" },
  HUN: { name: "Węgry", continent: "Europa" },
  ITA: { name: "Włochy", continent: "Europa" },
  JOR: { name: "Jordania", continent: "Azja" },
  KOR: { name: "Korea Południowa", continent: "Azja" },
  LTU: { name: "Litwa", continent: "Europa" },
  LVA: { name: "Łotwa", continent: "Europa" },
  MAR: { name: "Maroko", continent: "Afryka" },
  NOR: { name: "Norwegia", continent: "Europa" },
  PER: { name: "Peru", continent: "Ameryka Południowa" },
  POL: { name: "Polska", continent: "Europa" },
  PRT: { name: "Portugalia", continent: "Europa" },
  ROU: { name: "Rumunia", continent: "Europa" },
  SRB: { name: "Serbia", continent: "Europa" },
  SVK: { name: "Słowacja", continent: "Europa" },
  SVN: { name: "Słowenia", continent: "Europa" },
  SWE: { name: "Szwecja", continent: "Europa" },
  TZA: { name: "Tanzania", continent: "Afryka" },
  TUR: { name: "Turcja", continent: "Azja" },
  UKR: { name: "Ukraina", continent: "Europa" },
});

const travelers = Object.freeze([
  {
    id: "darek",
    name: "Darek",
    countries: [
      "POL",
      "ESP",
      "DEU",
      "PER",
      "MAR",
      "TZA",
      "ITA",
      "GBR",
      "SWE",
      "TUR",
      "JOR",
      "CZE",
      "AUT",
      "UKR",
      "ROU",
      "BGR",
      "SVN",
      "HRV",
      "SRB",
      "CYP",
      "BIH",
      "LTU",
      "HUN",
      "FIN",
      "SVK",
    ],
  },
  {
    id: "witek",
    name: "Witek",
    countries: ["POL", "ESP", "CZE", "CYP"],
  },
  {
    id: "ola",
    name: "Ola",
    countries: ["POL", "ESP", "CZE", "CYP", "ITA"],
  },
  {
    id: "tomek",
    name: "Tomek",
    countries: ["POL", "ESP", "CZE", "CYP", "HUN", "SVK", "ITA"],
  },
  {
    id: "daria",
    name: "Daria",
    countries: [
      "POL",
      "ESP",
      "CZE",
      "CYP",
      "HUN",
      "SVK",
      "ITA",
      "SVN",
      "BIH",
      "SRB",
      "BGR",
      "ROU",
      "HRV",
      "SWE",
      "NOR",
      "FIN",
      "DNK",
      "DEU",
      "FRA",
      "AUT",
      "CHE",
      "BEL",
      "KOR",
      "GBR",
      "PER",
      "PRT",
      "LTU",
      "LVA",
      "EST",
    ],
    countryLabelOverrides: {
      GBR: "Wielka Brytania (Anglia i Szkocja)",
    },
    mapNote:
      "Anglia i Szkocja są pokazane wspólnie jako Wielka Brytania, dlatego na mapie liczą się jako jeden kraj.",
  },
]);

// Zachowana nazwa z pierwszej wersji aplikacji dla zgodności wstecznej.
const visitedCountries = travelers[0].countries;
